services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ~/data:/data

  app:
    build: .
    container_name: event_deliver
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: 'redis'
    volumes:
      - ~/data:/data
      - ~/rdb_backups:/app/rdb_backups
      - ~/aof_backups:/app/aof_backups
    depends_on:
      - redis
