name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Lint
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint Code with pylint
      run: |
        pip install pylint
        pylint src/
      continue-on-error: true  # Continue even if pylint returns a non-zero exit code

    - name: Check pylint score
      run: |
        pylint_score=$(pylint --output-format=text src/ | grep -oE "Your code has been rated at [0-9]+\.[0-9]+" | tail -n 1 | awk -F ' ' '{print $7}')

        if [ -z "$pylint_score" ]; then
          echo "Linting score is not available. Failed the workflow."
          exit 1
        fi
        
        if [ $(echo "$pylint_score < 8" | bc -l) -eq 1 ]; then
          echo "Linting score is less than 8. Failed the workflow."
          exit 1
        fi
      
        
    - name: Run Tests
      run: |
        python -m pytest tests/
